# Generated by Django 3.1 on 2020-08-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0009_auto_20200807_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
