# Generated by Django 3.1.1 on 2020-09-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0013_auto_20200909_0256'),
    ]

    operations = [
        # migrations.RunSQL("INSERT INTO auth_group (name) VALUES ('admin');")
    ]
