# Generated by Django 3.1.1 on 2020-09-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0014_auto_20200924_0010'),
    ]

    operations = [
        # migrations.RunSQL("INSERT INTO auth_group (name) VALUES ('customers');")
    ]
