# Generated by Django 3.1.1 on 2020-10-04 03:55

import accountss.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0015_myapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/images/profile_pics/c188345d-a2ef-4b25-9d8a-ac9137926485-default_profile_pic.svg', null=True, upload_to=accountss.models.get_encoded_file_name),
        ),
    ]
